<section id="blog" class="container">
    <div class="blog">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="blog-ite wow fadeInDown">
                    <img class="img-responsive img-blog" src="resources/images/gift-card.jpg" width="100%" alt="" />
                </div><!--/.blog-item-->

                <div class="media reply_section wow fadeInDown">
                    <div class="media-body post_reply_content">
                        <h2>ENEM giftCard</h2>
                        <p>Una nueva revolución en los negocios ha comenzado, lanzándose la plataforma de negocios ENEM gifCard, el cual conecta el mercado tradicional y el Network Marketing, abriendo las puertas al mundo de los descuentos y brindando  a todas las personas una oportunidad de Negocios, que les permite hacer lo que siempre hacen con la diferencia de que puedan consumir, ahorrar y ganar dinero a la par.</p>
                        <p><strong>ENEM giftCard</strong> nació por la necesidad de poder ofrecer a todas las personas una oportunidad de negocios donde puedan aplicar sus conocimientos adquiridos para emprender, y que pueda ser la perfecta escuela o vehículo donde una persona pueda formarse, ganar experiencia y por sobre todo capitalizarse para luego poder invertir o emprender en lo que más le apasiona.</p>
                    </div>
                </div> 
            </div><!--/.col-md-8-->
        </div><!--/.row-->

    </div><!--/.blog-->

</section><!--/#blog-->