<section id="services" class="service-item">
    <div class="container">
        <div class="center wow fadeInDown">
            <h2>Enem Edu</h2>
            <p class="lead">Lograr un cambio radical en nuestras vidas, encontrar un camino hacia la felicidad</p>
        </div>

        <div class="row">
            <div class="col-sm-6 col-md-6">
                <div class="media services-wrap wow fadeInDown">
                    <div class="pull-left">
                        <img class="img-responsive" src="resources/images/services/services1.png">
                    </div>
                    <div class="media-body">
                        <p>El verdadero éxito radica en la felicidad y para alcanzarlo debes descubrir tu verdadero propósito y aprender a hacer aquello que amas.</p>
                    </div>
                </div>
            </div>

            <div class="col-sm-6 col-md-6">
                <div class="media services-wrap wow fadeInDown">
                    <div class="pull-left">
                        <img class="img-responsive" src="resources/images/services/services2.png">
                    </div>
                    <div class="media-body">
                        <p>Es ahí donde se encuentra el secreto para vivir una vida plena, donde comienzas a realizar tus proyectos por pasión y no por obligación.</p>
                    </div>
                </div>
            </div>

            <div class="col-sm-6 col-md-6">
                <div class="media services-wrap wow fadeInDown">
                    <div class="pull-left">
                        <img class="img-responsive" src="resources/images/services/services3.png">
                    </div>
                    <div class="media-body">
                        <p>Vivimos en un mundo donde la información cambia y avanza a velocidades sorprendentes, donde lo que aprendes hoy se desactualiza mañana. </p>
                    </div>
                </div>
            </div>  

            <div class="col-sm-6 col-md-6">
                <div class="media services-wrap wow fadeInDown">
                    <div class="pull-left">
                        <img class="img-responsive" src="resources/images/services/services4.png">
                    </div>
                    <div class="media-body">
                        <p>Esta nueva etapa economía  trajo consigo  varios cambios, el cual nos exige de nuevas informaciones para poder emprender y lograr el éxito en cualquier ámbito de nuestras vidas.</p>
                    </div>
                </div>
            </div>                                 
        </div><!--/.row-->
    </div><!--/.container-->
</section><!--/#services-->
<section id="enemedu" class="gray-bg">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="testimonial">
                    <div class="media testimonial-inner wow fadeInDownBig">
                        <div class="pull-left">
                            <img class="img-responsive img-circle" src="resources/images/testimonials1.png">
                        </div>
                        <div class="media-body">
                            <p><strong>ENEM Edu</strong> nace con el fin de poder brindar a todas las personas un modelo educativo integral, enfocado en el desarrollo del ser, que potencializa las capacidades de una persona y lo ayuda a descubrir su propósito.</p>
                        </div>
                    </div>

                    <div class="media testimonial-inner wow fadeInDownBig">
                        <div class="pull-left">
                            <img class="img-responsive img-circle" src="resources/images/testimonials1.png">
                        </div>
                        <div class="media-body">
                            <p>Un lugar donde puedas aprender tanto sobre la felicidad, el valor real de la vida, la amistad y el amor, como así también puedes aprender sobre el dinero y los negocios, a ser un líder, a comunicarte efectivamente con los demás, dotarte de  las mejores herramientas para vender y conseguir una negociación efectiva, a afrontar los miedos y canalizarlos para lograr el éxito y además aprenderás sobre Inteligencia emocional, coach en finanzas, y mucho más.</p>
                        </div>
                    </div>
                    
                    <div class="media testimonial-inner wow fadeInDownBig">
                        <div class="pull-left">
                            <img class="img-responsive img-circle" src="resources/images/testimonials1.png">
                        </div>
                        <div class="media-body">
                            <p><strong>Sin lugar a dudas te damos la bienvenida a la mejor plataforma educativa para desarrollar el SER.</strong></p>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div><!--/.container-->    
</section><!--/#conatcat-info-->
<section id="content">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12"> 
                <div class="accordion wow fadeInDown">
                    <div class="panel-group" id="accordion">
                        <div class="panel panel-default">
                            <div class="panel-heading active">
                                <h3 class="panel-title">
                                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#cursos">
                                        Cursos
                                        <i class="fa fa-angle-right pull-right"></i>
                                    </a>
                                </h3>
                            </div>

                            <div id="cursos" class="panel-collapse collapse in">
                                <div class="panel-body">
                                    <div class="media accordion-inner">
                                        <div class="pull-left">
                                            <img class="img-responsive" src="resources/images/accordion1.png">
                                        </div>
                                        <div class="media-body">
                                            <h4>Adipisicing elit</h4>
                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">
                                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#eventos">
                                        Eventos
                                        <i class="fa fa-angle-right pull-right"></i>
                                    </a>
                                </h3>
                            </div>
                            <div id="eventos" class="panel-collapse collapse">
                                <div class="panel-body">
                                    Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor.
                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">
                                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#registro">
                                        Registro
                                        <i class="fa fa-angle-right pull-right"></i>
                                    </a>
                                </h3>
                            </div>
                            <div id="registro" class="panel-collapse collapse">
                                <div class="panel-body">
                                    Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor.
                                </div>
                            </div>
                        </div>
                        
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">
                                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#calendario">
                                        Calendario
                                        <i class="fa fa-angle-right pull-right"></i>
                                    </a>
                                </h3>
                            </div>
                            <div id="calendario" class="panel-collapse collapse">
                                <div class="panel-body">
                                    Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor.
                                </div>
                            </div>
                        </div>
                    </div><!--/#accordion1-->
                </div>
            </div><!--/.col-sm-12-->
        </div><!--/.row-->
    </div><!--/.container-->
</section><!--/#content-->