</div>
</div>
<footer id="footer" class="midnight-blue">
    <div class="container">
        <div class="row">
            <div class="col-sm-4 col-xs-12">
                &copy; 2016 Enem. Todos los derechos reservados.
            </div>
            <div class="col-sm-4 col-xs-12">
                <div class="top-number"><p><i class="fa fa-phone-square"></i>  (0972) 197 397 |  (0991) 952 569</p></div>
            </div>
            <div class="col-sm-4 col-xs-12">
                <div class="social">
                    <ul class="social-share">
                        <li><a href="https://web.facebook.com/enemedu/"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="contacto.php"><i class="fa fa-envelope"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li> 
                        <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                        <li><a href="#"><i class="fa fa-skype"></i></a></li>
                    </ul>
                    <!--div class="search">
                        <form role="form">
                            <input type="text" class="search-form" autocomplete="off" placeholder="Search">
                            <i class="fa fa-search"></i>
                        </form>
                   </div-->
                </div>
            </div>
        </div>
</footer><!--/#footer-->

<script src="resources/js/jquery.js"></script>
<script src="resources/js/angular.min.js"></script>
<script src="resources/js/angular-cookies.min.js"></script>
<script src="resources/js/angular-ui-router.min.js"></script>
<script src="resources/js/bootstrap.min.js"></script>
<script src="resources/js/bootstrap-datepicker.js"></script>
<script src="resources/js/d3.v3.min.js"></script>
<!--script src="resources/js/enem.min.js?<?php echo(rand()); ?> "></script-->
<script src="resources/js/main.js"></script>
<script src="resources/js/easymodal.min.js"></script>
<script src="resources/js/wow.min.js"></script>
</body>
</html>