        <footer id="footer" class="midnight-blue">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        &copy; 2016 Enem. Todos los derechos reservados.
                    </div>
                    <div class="col-sm-offset-6">
                        
                    </div>
                </div>
            </div>
        </footer><!--/#footer-->

        <script src="resources/js/jquery.js"></script>
        <script src="resources/js/angular.min.js"></script>
        <script src="resources/js/bootstrap.min.js"></script>
        <script src="resources/js/jquery.prettyPhoto.js"></script>
        <script src="resources/js/jquery.isotope.min.js"></script>
        <script src="resources/js/bootstrap-datepicker.js"></script>
        <script src="resources/js/main.js"></script>
        <script src="resources/js/wow.min.js"></script>
    </body>
</html>