        <footer id="footer" class="midnight-blue">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        &copy; 2016 Enem. Todos los derechos reservados.
                    </div>
                    <div class="col-sm-6">
                        <ul class="pull-right">
                            <li><a href="index.html">Inicio</a></li>
                            <li><a href="nosotros.html">Nosotros</a></li>
                            <li><a href="edu.html">Enem Edu</a></li>
                            <li><a href="business.html">Enem Business</a></li>
                            <li><a href="contacto.html">Contacto</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer><!--/#footer-->

        <script src="resources/js/jquery.js"></script>
        <script src="resources/js/angular.min.js"></script>
        <script src="resources/js/bootstrap.min.js"></script>
        <script src="resources/js/jquery.prettyPhoto.js"></script>
        <script src="resources/js/jquery.isotope.min.js"></script>
        <script src="resources/js/main.js"></script>
        <script src="resources/js/wow.min.js"></script>
    </body>
</html>