<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>ENEM | Despertando Sue&ntilde;os</title>

        <!-- core CSS -->
        <link href="resources/css/bootstrap.min.css" rel="stylesheet">
        <link href="resources/css/font-awesome.min.css" rel="stylesheet">
        <link href="resources/css/animate.min.css" rel="stylesheet">
        <link href="resources/css/prettyPhoto.css" rel="stylesheet">
        <link href="resources/css/main.css" rel="stylesheet">
        <link href="resources/css/responsive.css" rel="stylesheet">
        <link href="resources/css/datepicker.css" rel="stylesheet">
        <!--[if lt IE 9]>
        <script src="js/html5shiv.js"></script>
        <script src="js/respond.min.js"></script>
        <![endif]-->       
        <link rel="shortcut icon" href="resources/images/ico/favicon.ico">
    </head><!--/head-->

    <body class="homepage">

        <header id="header">
            <div class="top-bar">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-6 col-xs-4">
                            <div class="top-number"><p><i class="fa fa-phone-square"></i>  (0972) 197 397</p></div>
                            <div class="top-number"><p><i class="fa fa-phone-square"></i>  (0991) 952 569</p></div>                 
                        </div>
                        <div class="col-sm-6 col-xs-8">
                            <div class="social">
                                <ul class="social-share">
                                    <li><a href="https://web.facebook.com/enemedu/"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="contacto.php"><i class="fa fa-envelope"></i></a></li>
                                    <li><a href="#"><i class="fa fa-linkedin"></i></a></li> 
                                    <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                                    <li><a href="#"><i class="fa fa-skype"></i></a></li>
                                </ul>
                                <!--div class="search">
                                    <form role="form">
                                        <input type="text" class="search-form" autocomplete="off" placeholder="Search">
                                        <i class="fa fa-search"></i>
                                    </form>
                               </div-->
                            </div>
                        </div>
                    </div>
                </div><!--/.container-->
            </div><!--/.top-bar-->

            <nav class="navbar navbar-inverse" role="banner">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="index.php"><img src="resources/images/logo-web.png" alt="logo"></a>
                    </div>

                    <div class="collapse navbar-collapse navbar-right">
                        <ul class="nav navbar-nav">
                            <li><a href="index.php">Inicio</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Nosotros <i class="fa fa-angle-down"></i></a>
                                <ul class="dropdown-menu">
                                    <li><a href="nosotros.php">Conocenos</a></li>
                                    <li><a href="nosotros.php#mision">Misi&oacute;n</a></li>
                                    <li><a href="nosotros.php#vision">Visi&oacute;n</a></li>
                                    <li><a href="nosotros.php#management">Management</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Enem Edu <i class="fa fa-angle-down"></i></a>
                                <ul class="dropdown-menu">
                                    <li><a href="edu.php">¿Qu&eacute; es Enem Edu?</a></li>
                                    <li><a href="edu.php#cursos">Cursos</a></li>
                                    <li><a href="edu.php#eventos">Eventos</a></li>
                                    <li><a href="edu.php#registros">Registro</a></li>
                                    <li><a href="edu.php#calendario">Calendario</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="business.html" class="dropdown-toggle" data-toggle="dropdown">Enem Business <i class="fa fa-angle-down"></i></a>
                                <ul class="dropdown-menu">
                                    <li><a href="business.php?login">Login</a></li>
                                    <li><a href="business.php?registro">Registrate</a></li>
                                    <li><a href="business.php">Conoc&eacute; ENEM giftCard</a></li>
                                </ul>
                            </li>
                            <li><a href="contacto.php">Contacto</a></li>
                            <li><a href="admin.php">Administraci&oacute;n</a></li>
                        </ul>
                    </div>
                </div><!--/.container-->
            </nav><!--/nav-->
        </header><!--/header-->