<!-- Content -->
<section id="main-slider" class="no-margin">
    <div class="carousel slide">
        <ol class="carousel-indicators">
            <li data-target="#main-slider" data-slide-to="0" class="active"></li>
            <li data-target="#main-slider" data-slide-to="1"></li>
        </ol>
        <div class="carousel-inner">

            <div class="item active" style="background-image: url(resources/images/slider/bg1.jpg)">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="carousel-content">
                                <h1 class="animation animated-item-1">ENEM</h1>
                                <h2 class="animation animated-item-2">Empresarios de la Nueva Econom&iacute;a Mundial</h2>
                                <a class="btn-slide animation animated-item-3" href="business.php">Enem Business</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--/.item-->

            <div class="item" style="background-image: url(resources/images/slider/bg2.jpg)">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="carousel-content">
                                <h1 class="animation animated-item-1">ENEM</h1>
                                <h2 class="animation animated-item-2">Educaci&oacute;n de la Nueva Econom&iacute;a Mundial</h2>
                                <a class="btn-slide animation animated-item-3" href="edu.php">Read More</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--/.item-->            
        </div><!--/.carousel-inner-->
    </div><!--/.carousel-->
    <a class="prev hidden-xs" href="#main-slider" data-slide="prev">
        <i class="fa fa-chevron-left"></i>
    </a>
    <a class="next hidden-xs" href="#main-slider" data-slide="next">
        <i class="fa fa-chevron-right"></i>
    </a>
</section><!--/#main-slider-->