<section id="about-us">
    <div class="container">
        <div class="center wow fadeInDown">
            <h2>ENEM. Empresarios de la Nueva Economía Mundial.</h2>
            <p class="lead">Bienvenidos a la mejor plataforma educativa y de negocios.</p>
        </div>

        <!-- about us slider -->
        <div id="about-slider">
            <div id="carousel-slider" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators visible-xs">
                    <li data-target="#carousel-slider" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-slider" data-slide-to="1"></li>
                </ol>

                <div class="carousel-inner">
                    <div class="item active">
                        <img src="resources/images/logo-enem-colores-letras-negras.png" class="img-responsive" alt=""> 
                    </div>
                    <div class="item">
                        <img src="resources/images/slider_one.jpg" class="img-responsive" alt=""> 
                    </div> 
                </div>

                <a class="left carousel-control hidden-xs" href="#carousel-slider" data-slide="prev">
                    <i class="fa fa-chevron-left"></i> 
                </a>

                <a class=" right carousel-control hidden-xs"href="#carousel-slider" data-slide="next">
                    <i class="fa fa-chevron-right"></i> 
                </a>
            </div> <!--/#carousel-slider-->
        </div><!--/#about-slider-->
</section>
<section id="feature">
    <div class="container">
        <div class="center wow fadeInDown">
            <h2>¿Qu&eacute; te brindamos?</h2>
        </div>

        <div class="row">
            <div class="features">
                <div class="col-md-6 col-sm-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                    <div class="feature-wrap">
                        <i class="fa fa-check"></i>
                        <h2>Información</h2>
                        <h3>Basada en experiencias de personas que han alcanzado el éxito</h3>
                    </div>
                </div><!--/.col-md-4-->

                <div class="col-md-6 col-sm-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                    <div class="feature-wrap">
                        <i class="fa fa-arrow-up"></i>
                        <h2>Crecimiento/Desarrollo</h2>
                        <h3>Te ayudaremos a crecer, a desarrollarte como persona, como empresario</h3>
                    </div>
                </div><!--/.col-md-4-->

                <div class="col-md-6 col-sm-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                    <div class="feature-wrap">
                        <i class="fa fa-pencil"></i>
                        <h2>Enseñanza</h2>
                        <h3>Te enseñaremos a como encontrarte a ti mismo para descubrir tu verdadero potencial</h3>
                    </div>
                </div><!--/.col-md-4-->

                <div class="col-md-6 col-sm-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                    <div class="feature-wrap">
                        <i class="fa fa-comments"></i>
                        <h2>Gu&iacute;a</h2>
                        <h3>Te dotaremos de cualidades y herramientas de negocios para poder ser prospero en esta nueva económica</h3>
                    </div>
                </div><!--/.col-md-4-->

            </div><!--/.services-->
        </div><!--/.row-->    
    </div><!--/.container-->
</section><!--/#feature-->

<section id="team">
    <!-- our-team -->
    <div class="team">
        <div class="center wow fadeInDown">
            <h2>El equipo de ENEM</h2>
            <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut <br> et dolore magna aliqua. Ut enim ad minim veniam</p>
        </div>

        <div class="row clearfix">
            <div class="col-md-4 col-sm-6">	
                <div class="single-profile-top wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                    <div class="media">
                        <div class="pull-left">
                            <a href="#"><img class="media-object" src="resources/images/man1.jpg" alt=""></a>
                        </div>
                        <div class="media-body">
                            <h4>Jhon Doe</h4>
                            <h5>Founder and CEO</h5>
                            <ul class="tag clearfix">
                                <li class="btn"><a href="#">Web</a></li>
                                <li class="btn"><a href="#">Ui</a></li>
                                <li class="btn"><a href="#">Ux</a></li>
                                <li class="btn"><a href="#">Photoshop</a></li>
                            </ul>

                            <ul class="social_icons">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li> 
                                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                    </div><!--/.media -->
                    <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.</p>
                </div>
            </div><!--/.col-lg-4 -->


            <div class="col-md-4 col-sm-6 col-md-offset-2">	
                <div class="single-profile-top wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                    <div class="media">
                        <div class="pull-left">
                            <a href="#"><img class="media-object" src="resources/images/man2.jpg" alt=""></a>
                        </div>
                        <div class="media-body">
                            <h4>Jhon Doe</h4>
                            <h5>Founder and CEO</h5>
                            <ul class="tag clearfix">
                                <li class="btn"><a href="#">Web</a></li>
                                <li class="btn"><a href="#">Ui</a></li>
                                <li class="btn"><a href="#">Ux</a></li>
                                <li class="btn"><a href="#">Photoshop</a></li>
                            </ul>
                            <ul class="social_icons">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li> 
                                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                    </div><!--/.media -->
                    <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.</p>
                </div>
            </div><!--/.col-lg-4 -->					
        </div> <!--/.row -->
        <div class="row team-bar">
            <div class="first-one-arrow hidden-xs">
                <hr>
            </div>
            <div class="first-arrow hidden-xs">
                <hr> <i class="fa fa-angle-up"></i>
            </div>
            <div class="second-arrow hidden-xs">
                <hr> <i class="fa fa-angle-down"></i>
            </div>
            <div class="third-arrow hidden-xs">
                <hr> <i class="fa fa-angle-up"></i>
            </div>
            <div class="fourth-arrow hidden-xs">
                <hr> <i class="fa fa-angle-down"></i>
            </div>
        </div> <!--skill_border-->       

        <div class="row clearfix">   
            <div class="col-md-4 col-sm-6 col-md-offset-2">	
                <div class="single-profile-bottom wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="600ms">
                    <div class="media">
                        <div class="pull-left">
                            <a href="#"><img class="media-object" src="resources/images/man3.jpg" alt=""></a>
                        </div>

                        <div class="media-body">
                            <h4>Jhon Doe</h4>
                            <h5>Founder and CEO</h5>
                            <ul class="tag clearfix">
                                <li class="btn"><a href="#">Web</a></li>
                                <li class="btn"><a href="#">Ui</a></li>
                                <li class="btn"><a href="#">Ux</a></li>
                                <li class="btn"><a href="#">Photoshop</a></li>
                            </ul>
                            <ul class="social_icons">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li> 
                                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                    </div><!--/.media -->
                    <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.</p>
                </div>
            </div>
            <div class="col-md-4 col-sm-6 col-md-offset-2">
                <div class="single-profile-bottom wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="600ms">
                    <div class="media">
                        <div class="pull-left">
                            <a href="#"><img class="media-object" src="resources/images/man4.jpg" alt=""></a>
                        </div>
                        <div class="media-body">
                            <h4>Jhon Doe</h4>
                            <h5>Founder and CEO</h5>
                            <ul class="tag clearfix">
                                <li class="btn"><a href="#">Web</a></li>
                                <li class="btn"><a href="#">Ui</a></li>
                                <li class="btn"><a href="#">Ux</a></li>
                                <li class="btn"><a href="#">Photoshop</a></li>
                            </ul>
                            <ul class="social_icons">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li> 
                                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                    </div><!--/.media -->
                    <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.</p>
                </div>
            </div>
        </div>	<!--/.row-->
    </div><!--section-->
</div><!--/.container-->
</section><!--/about-us-->
<section id="content" class="gray-bg">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12"> 
                <div class="tab-wrap">
                    <div class="media wow fadeInDown">
                        <div class="parrent pull-left">
                            <ul class="nav nav-tabs nav-stacked">
                                <li class="active"><a href="#mision" data-toggle="tab" class="analistic-01">Misi&oacute;n</a></li>
                                <li class=""><a href="#vision" data-toggle="tab" class="analistic-02">Visi&oacute;n</a></li>
                            </ul>
                        </div>

                        <div class="parrent media-body">
                            <div class="tab-content">
                                <div class="tab-pane" id="mision">
                                    <div class="media">
                                        <div class="pull-left">
                                            <img class="img-responsive" src="resources/images/tab1.png">
                                        </div>
                                        <div class="media-body">
                                            <h4>Misi&oacute;n</h4>
                                            <p>Somos una empresa que nació por una necesidad de cambio, que se atreve a romper paradigmas e implementar una educación integral, que se enfoca en el desarrollo del Ser de las personas.</p>
                                            <p>Implementamos un sistema educacional apto para todo público, el cual redescubre a las personas, donde los enseña  a creer nuevamente en sí mismo, saber de sus potenciales y que nazca en ellos un deseo ardiente para salir a luchar y conquistar sus sueños.</p>
                                            <p>Además de poder brindar de herramientas útiles y oportunidades de negocios para ser competitivo en la nueva economía. </p>
                                        </div>
                                    </div>
                                </div>

                                <div class="tab-pane active in" id="vision">
                                    <div class="media">
                                        <div class="pull-left">
                                            <img class="img-responsive" src="resources/images/tab2.png">
                                        </div>
                                        <div class="media-body">
                                            <h4>Visi&oacute;n</h4>
                                            <p>Ser la mayor plataforma educativa y de oportunidad de negocios, que sea capaz de crear una mentalidad de éxito en las personas, donde la riqueza que abarca en la parte personal, familiar, social y económica, sean las bases fundamentales de logros y metas.</p>
                                            <p>Implementar una nueva cultura social en las personas de cualquier edad que estén dispuestas al cambio donde puedan mantener una correcta educación, que sea flexible y adaptable para lograr ser felices y prósperos.</p>
                                            <p>Una plataforma donde todas las personas puedan recibir conocimientos de economía y desarrollo personal, donde aprendan  a analizar las oportunidades que trae consigo esta nueva etapa económica y aquellas oportunidades  que van naciendo día a día y por sobre poder bridarles una plataforma de negocios donde puedan aplicar todos sus conocimientos adquiridos y comenzar a trabajar para cumplir sus sueños y lograr obtener libertad de tiempo y dinero.</p>
                                        </div>
                                    </div>
                                </div>
                            </div> <!--/.tab-content-->  
                        </div> <!--/.media-body--> 
                    </div> <!--/.media-->     
                </div><!--/.tab-wrap-->               
            </div><!--/.col-sm-12-->
        </div><!--/.row-->
    </div><!--/.container-->
</section><!--/#content-->