<section>
    <div class="container">
        <div class="center wow fadeInDown">        
            <h2>Registrate</h2>
            <p class="lead">Enem. Empresaros de la Nueva Econom&iacute;a Mundial</p>
        </div> 
        <div class="status alert alert-success" style="display: none"></div>
        <form id="main-contact-form" class="contact-form" name="contact-form" method="post" action="">
            <div class="row contact-wrap"> 
                <div class="col-sm-6 wow fadeInDown">
                    <div class="form-group">
                        <label>Patrocinador</label>
                        <input type="text" name="patrocinador" class="form-control focused" required="required">
                    </div>
                </div>
                <div class="col-sm-6 wow fadeInDown">
                    <div class="form-group">
                        <label>Codigo de promoci&oacute;n</label>
                        <input type="text" name="promocode" class="form-control" required="required">
                    </div>
                </div>
            </div>
            <div class="row contact-wrap"> 
                <div class="col-sm-4 wow fadeInDown">
                    <div class="form-group">
                        <label>Nombre de Usuario *</label>
                        <input type="text" name="nombreusuario" class="form-control" required="required">
                    </div>
                    <div class="form-group">
                        <label>Nombre *</label>
                        <input type="text" name="nombre" class="form-control" required="required">
                    </div>
                    <div class="form-group">
                        <label>Email</label>
                        <input type="email" class="form-control">
                    </div>    
                    <div class="form-group">
                        <label>Dirección</label>
                        <input type="text" class="form-control">
                    </div>
                </div>
                <div class="col-sm-4 wow fadeInDown">
                    <div class="form-group">
                        <label>Contrase&ntilde;a *</label>
                        <input type="text" name="nombreusuario" class="form-control" required="required">
                    </div>
                    <div class="form-group">
                        <label>Apellido *</label>
                        <input type="text" name="nombre" class="form-control" required="required">
                    </div>
                    <div class="form-group">
                        <label>Confirmar Email</label>
                        <input type="email" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Ciudad</label>
                        <input type="text" class="form-control">
                    </div>                        
                </div>
                <div class="col-sm-4 wow fadeInDown">
                    <div class="form-group">
                        <label>Confirmar Contrase&ntilde;a</label>
                        <input type="text" name="subject" class="form-control" required="required">
                    </div>
                    <div class="form-group">
                        <label>G&eacute;nero</label>
                        <input type="text" class="form-control">
                    </div>                        
                    <div class="form-group">
                        <label>Fecha de Nacimiento</label>
                        <input type="text" class="form-control">
                    </div> 
                    <div class="form-group">
                        <label>Tel&eacute;fono</label>
                        <input type="text" class="form-control">
                    </div> 
                    <div class="form-group">
                        <button type="submit" name="submit" class="btn btn-primary btn-lg" required="required">Registrarme</button>
                    </div>
                </div>
            </div><!--/.row-->
        </form> 
    </div><!--/.container-->
</section><!--/#contact-page-->
