<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="wow fadeInDown">
                    <img class="img-responsive img-blog" src="resources/images/enem/gift-card.jpg" width="100%" alt="" />
                </div>
                <br/>
                <div class="media services-wrap wow fadeInDown">
                    <div class="media-body">
                        <h2>ENEM giftCard</h2>
                        <p>Una nueva revolución en los negocios ha comenzado, lanzándose la plataforma de negocios ENEM gifCard, el cual conecta el mercado tradicional y el Network Marketing, abriendo las puertas al mundo de los descuentos y brindando  a todas las personas una oportunidad de Negocios, que les permite hacer lo que siempre hacen con la diferencia de que puedan consumir, ahorrar y ganar dinero a la par.</p>
                        <p><strong>ENEM giftCard</strong> nació por la necesidad de poder ofrecer a todas las personas una oportunidad de negocios donde puedan aplicar sus conocimientos adquiridos para emprender, y que pueda ser la perfecta escuela o vehículo donde una persona pueda formarse, ganar experiencia y por sobre todo capitalizarse para luego poder invertir o emprender en lo que más le apasiona.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="partner">
        <div class="container">
            <div class="center wow fadeInDown">
                <h2>Locales Adheridos</h2>
                <p class="lead">Conozca nuestros locales adheridos</p>
            </div>    

            <div class="partners">
                <ul>
                    <li> <a href="#"><img class="img-responsive wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms" src="resources/images/partners/partner1.png"></a></li>
                    <li> <a href="#"><img class="img-responsive wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms" src="resources/images/partners/partner2.png"></a></li>
                    <li> <a href="#"><img class="img-responsive wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="900ms" src="resources/images/partners/partner3.png"></a></li>
                    <li> <a href="#"><img class="img-responsive wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="1200ms" src="resources/images/partners/partner4.png"></a></li>
                    <li> <a href="#"><img class="img-responsive wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="1500ms" src="resources/images/partners/partner5.png"></a></li>
                </ul>
            </div>        
        </div><!--/.container-->
    </section><!--/#partner-->