<section id="services">
    <!-- our-team -->
    <div class="team">
        <div class="center wow fadeInDown">
            <h2>El equipo de ENEM</h2>
        </div>

        <div class="row clearfix">
            <div class="col-md-4 col-sm-6">	
                <div class="single-profile-top wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                    <div class="media">
                        <div class="pull-left">
                            <a href="#"><img class="media-object" src="resources/images/enem/sergio-cropped.jpg" alt=""></a>
                        </div>
                        <div class="media-body">
                            <h4>Sergio Morinigo</h4>
                            <h5>CEO Fundador</h5>
                            <p>Empresario conferencista.</p>
                            <ul class="social_icons">
                                <li><a href="https://www.facebook.com/sergiojavier.morinigomarecos"><i class="fa fa-facebook"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>


            <div class="col-md-4 col-sm-6 col-md-offset-2">	
                <div class="single-profile-top wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                    <div class="media">
                        <div class="pull-left">
                            <a href="#"><img class="media-object" src="resources/images/enem/gus-cropped.jpg" alt=""></a>
                        </div>
                        <div class="media-body">
                            <h4>Dardo Rios</h4>
                            <h5>CEO Fundador</h5>
                            <p>Empresario conferencista.</p>
                            <ul class="social_icons">
                                <li><a href="https://www.facebook.com/softsimparaguay"><i class="fa fa-facebook"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>		
        </div>
        <div class="row team-bar">
            <div class="first-one-arrow hidden-xs">
                <hr>
            </div>
            <div class="first-arrow hidden-xs">
                <hr> <i class="fa fa-angle-up"></i>
            </div>
            <div class="second-arrow hidden-xs">
                <hr> <i class="fa fa-angle-down"></i>
            </div>
            <div class="third-arrow hidden-xs">
                <hr> <i class="fa fa-angle-up"></i>
            </div>
            <div class="fourth-arrow hidden-xs">
                <hr> <i class="fa fa-angle-down"></i>
            </div>
        </div> <!--skill_border-->       

        <!--div class="row clearfix">   
            <div class="col-md-4 col-sm-6 col-md-offset-2">	
                <div class="single-profile-bottom wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="600ms">
                    <div class="media">
                        <div class="pull-left">
                            <a href="#"><img class="media-object" src="resources/images/enem/g.jpg" alt=""></a>
                        </div>

                        <div class="media-body">
                            <h4>Nombre Apellido</h4>
                            <h5>CEO</h5>
                            <ul class="social_icons">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li> 
                                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <p>Empresario conferencista.</p>
                </div>
            </div>
            <div class="col-md-4 col-sm-6 col-md-offset-2">
                <div class="single-profile-bottom wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="600ms">
                    <div class="media">
                        <div class="pull-left">
                            <a href="#"><img class="media-object" src="resources/images/man4.jpg" alt=""></a>
                        </div>
                        <div class="media-body">
                            <h4>Sergio Morinigo</h4>
                            <h5>Fundador y CEO</h5>
                            <ul class="social_icons">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li> 
                                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <p>Empresario conferencista.</p>
                </div>
            </div>
        </div-->
    </div>
</section>
