<section id="services">
    <div class="container">
        <div class="center wow fadeInDown">
            <h2>Misión / Visión</h2>
        </div>
        
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <div class="media services-wrap wow fadeInDown">
                    <div class="pull-left">
                        <img class="img-responsive" src="resources/images/services/services1.png">
                    </div>
                    <div class="media-body">
                        <h3>Misión</h3>
                        <p>Somos una empresa que nació por una necesidad de cambio, que se atreve a romper paradigmas e implementar una educación integral, que se enfoca en el desarrollo del Ser de las personas.</p>
                        <p>Implementamos un sistema educacional apto para todo público, el cual redescubre a las personas, donde los enseña  a creer nuevamente en sí mismo, saber de sus potenciales y que nazca en ellos un deseo ardiente para salir a luchar y conquistar sus sueños.</p>
                        <p>Además de poder brindar de herramientas útiles y oportunidades de negocios para ser competitivo en la nueva economía. </p>
                    </div>
                </div>
            </div>

            <div class="col-sm-12 col-md-12">
                <div class="media services-wrap wow fadeInDown">
                    <div class="pull-left">
                        <img class="img-responsive" src="resources/images/services/services2.png">
                    </div>
                    <div class="media-body">
                        <h3>Visión</h3>
                        <p>Ser la mayor plataforma educativa y de oportunidad de negocios, que sea capaz de crear una mentalidad de éxito en las personas, donde la riqueza que abarca en la parte personal, familiar, social y económica, sean las bases fundamentales de logros y metas.</p>
                        <p>Implementar una nueva cultura social en las personas de cualquier edad que estén dispuestas al cambio donde puedan mantener una correcta educación, que sea flexible y adaptable para lograr ser felices y prósperos.</p>
                        <p>Una plataforma donde todas las personas puedan recibir conocimientos de economía y desarrollo personal, donde aprendan  a analizar las oportunidades que trae consigo esta nueva etapa económica y aquellas oportunidades  que van naciendo día a día y por sobre poder bridarles una plataforma de negocios donde puedan aplicar todos sus conocimientos adquiridos y comenzar a trabajar para cumplir sus sueños y lograr obtener libertad de tiempo y dinero.</p>
                    </div>
                </div>
            </div>                               
        </div>
    </div>
</section>