<section id="services">
    <div class="container">
        <div class="center wow fadeInDown">
            <h2>ENEM. Empresarios de la Nueva Economía Mundial.</h2>
            <p class="lead">Bienvenidos a la mejor plataforma educativa y de negocios.</p>
        </div>

        <div id="about-slider">
            <div id="carousel-slider" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators visible-xs">
                    <li data-target="#carousel-slider" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-slider" data-slide-to="1"></li>
                </ol>

                <div class="carousel-inner">
                    <div class="item active">
                        <img src="resources/images/enem/logo-enem-colores-letras-negras.png" class="img-responsive" alt=""> 
                    </div>
                    <div class="item">
                        <img src="resources/images/slider_one.jpg" class="img-responsive" alt=""> 
                    </div> 
                </div>

                <a class="left carousel-control hidden-xs" href="#carousel-slider" data-slide="prev">
                    <i class="fa fa-chevron-left"></i> 
                </a>

                <a class=" right carousel-control hidden-xs"href="#carousel-slider" data-slide="next">
                    <i class="fa fa-chevron-right"></i> 
                </a>
            </div>
        </div>

        <br /><br /><br /><br />

        <div class="center wow fadeInDown">
            <h2>¿Qu&eacute; te brindamos?</h2>
        </div>

        <div class="row">
            <div class="col-sm-6 col-md-6">
                <div class="media services-wrap wow fadeInDown">
                    <div class="pull-left">
                        <img class="img-responsive" src="resources/images/enem/1.png">
                    </div>
                    <div class="media-body">
                        <h3><strong>Información</strong> basada en experiencias de personas que han alcanzado el éxito</h3>
                    </div>
                </div>
            </div>

            <div class="col-sm-6 col-md-6">
                <div class="media services-wrap wow fadeInDown">
                    <div class="pull-left">
                        <img class="img-responsive" src="resources/images/enem/2.png">
                    </div>
                    <div class="media-body">
                        <h3>Te ayudaremos a crecer, a desarrollarte como persona, como empresario</h3>
                    </div>
                </div>
            </div>

            <div class="col-sm-6 col-md-6">
                <div class="media services-wrap wow fadeInDown">
                    <div class="pull-left">
                        <img class="img-responsive" src="resources/images/enem/3.png">
                    </div>
                    <div class="media-body">
                        <h3>Te enseñaremos a como encontrarte a ti mismo para descubrir tu verdadero potencial</h3>
                    </div>
                </div>
            </div>  

            <div class="col-sm-6 col-md-6">
                <div class="media services-wrap wow fadeInDown">
                    <div class="pull-left">
                        <img class="img-responsive" src="resources/images/enem/4.png">
                    </div>
                    <div class="media-body">
                        <h3>Te dotaremos de cualidades y herramientas de negocios para poder ser prospero en esta nueva económica</h3>
                    </div>
                </div>
            </div>                                 
        </div>
    </div>
</section>